name: Rbsyn Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.2']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Build and quick test with Rake
      run: |
        sudo apt-get install -y libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake smallbench
